# Reto 2 – Condicionales y filtros

En este reto se analizan los datos de calidad del agua utilizando filtros y condiciones lógicas para clasificar el estado del sistema.

In [3]:
import pandas as pd

df = pd.read_csv("../datos/datos_experimentales.csv")

df.head()

             punto  dureza  conductividad   ph  oxigeno  temperatura
0   Rio mancilla 1      85            160  6.8      7.4           18
1   Rio Mancilla 2     230            320  6.1      5.6           19
2      Rio Botello     190            270  6.0      5.3           20
3  Rio Cartagenita     360            520  6.4      3.2           22

In [5]:
df.info()

df.describe()

df.columns

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   punto          4 non-null      str
 1   dureza         4 non-null      int64
 2   conductividad  4 non-null      int64
 3   ph             4 non-null      float64
 4   oxigeno        4 non-null      float64
 5   temperatura    4 non-null      int64
dtypes: float64(2), int64(3), str(1)
memory usage: 324.0 bytes

Index(['punto', 'dureza', 'conductividad', 'ph', 'oxigeno', 'temperatura'], dtype='str')

In [6]:
df["estado"] = "Normal"

df.head()

             punto  dureza  conductividad   ph  oxigeno  temperatura  estado
0   Rio mancilla 1      85            160  6.8      7.4           18  Normal
1   Rio Mancilla 2     230            320  6.1      5.6           19  Normal
2      Rio Botello     190            270  6.0      5.3           20  Normal
3  Rio Cartagenita     360            520  6.4      3.2           22  Normal

In [7]:
df.loc[
    (df["oxigeno"] < 5),
    "estado"
] = "En riesgo"

df.head()

,punto,dureza,conductividad,ph,oxigeno,temperatura,estado
0,Rio mancilla 1,85,160,6.8,7.4,18,Normal
1,Rio Mancilla 2,230,320,6.1,5.6,19,Normal
2,Rio Botello,190,270,6.0,5.3,20,Normal
3,Rio Cartagenita,360,520,6.4,3.2,22,En riesgo

In [8]:
df.loc[
    (df["temperatura"] > 25),
    "estado"
] = "En riesgo"

df.head()

,punto,dureza,conductividad,ph,oxigeno,temperatura,estado
0,Rio mancilla 1,85,160,6.8,7.4,18,Normal
1,Rio Mancilla 2,230,320,6.1,5.6,19,Normal
2,Rio Botello,190,270,6.0,5.3,20,Normal
3,Rio Cartagenita,360,520,6.4,3.2,22,En riesgo

In [9]:
df["estado"].value_counts()

estado
Normal       3
En riesgo    1
Name: count, dtype: int64

In [10]:
df["clasificacion"] = "Estable"

df.loc[
    (df["oxigeno"] < 5),
    "clasificacion"
] = "Critico"

df.loc[
    (df["temperatura"] > 25),
    "clasificacion"
] = "Moderado"

df.head()

,punto,dureza,conductividad,ph,oxigeno,temperatura,estado,clasificacion
0,Rio mancilla 1,85,160,6.8,7.4,18,Normal,Estable
1,Rio Mancilla 2,230,320,6.1,5.6,19,Normal,Estable
2,Rio Botello,190,270,6.0,5.3,20,Normal,Estable
3,Rio Cartagenita,360,520,6.4,3.2,22,En riesgo,Critico

In [11]:
df["clasificacion"].value_counts()

clasificacion
Estable    3
Critico    1
Name: count, dtype: int64

## Interpretación de resultados

A partir de los filtros y condiciones aplicadas se identificaron registros en diferentes estados de riesgo.

Las temperaturas elevadas y los niveles bajos de oxígeno representan condiciones que pueden afectar la calidad del agua y generar estrés en los organismos acuáticos.

La clasificación detallada permitió organizar los datos en categorías como estable, moderado y crítico, facilitando la interpretación del comportamiento del sistema.